data_root_dir: /data/yuxi
hf_token: .hf_token
image_aug: true
is_resume: true
pretrained_checkpoint: null
resume_epoch: null
resume_step: null
run_id: siglip-224px+mx-bridge+n0+b8+x7--single-gpu-test--image_aug
run_id_note: single-gpu-test
run_root_dir: runs/modified_libero_finetune
save_interval: 2500
seed: 7
trackers:
- jsonl
- wandb
vla:
  base_vlm: siglip-224px+7b
  data_mix: bridge
  enable_gradient_checkpointing: true
  enable_mixed_precision_training: true
  epochs: 1000
  expected_world_size: 1
  freeze_llm_backbone: false
  freeze_vision_backbone: false
  global_batch_size: 8
  learning_rate: 2.0e-05
  lr_scheduler_type: constant
  max_grad_norm: 1.0
  max_steps: null
  per_device_batch_size: 8
  reduce_in_full_precision: true
  shuffle_buffer_size: 256000
  train_strategy: fsdp-full-shard
  type: dino+siglip-224px_llama-2-7b_modified-libero
  unfreeze_last_llm_layer: false
  vla_id: siglip-224px+mx-bridge
  warmup_ratio: 0.0
  weight_decay: 0.0
wandb_entity: stanford-voltron
wandb_project: openvla-finetune
